ADD documentation product epic to handbook
thoth-tech/handbook pull request #51
Opened 2022-04-05 09:25 UTC by j-6

_Any italic text should be deleted from the final Pull Request text, including this line_

# Description

_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change._

Fixes # (issue)

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (update or new)

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_

## Testing Checklist:

- [ ] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

2022-04-05 10:49 UTC, j-6 commented
@ginge270 can you pelase provide some insight into these failed checks?

2022-04-05 13:58 UTC, ginge270 approved these changes
Awesome job 🥇

2022-04-06 12:20 UTC, tancnle commented on docs/products/ontrack/project-epics/documentation-epic.md
> +Requirement documentation
**issue:** Could we convert this to an unordered list? This is rendered as one line at the moment.

2022-04-06 12:23 UTC, tancnle requested changes
Thanks, @j-6. I have left some suggestions for your consideration. Please let me know what you think.

Is this PR ready for review? I noted that this is still set as draft 🤔

2022-04-06 12:23 UTC, tancnle commented on docs/products/ontrack/project-epics/documentation-epic.md
> +User research documentation
issue: Similar suggestion as above. Could we convert this to an unordered list?

2022-04-06 12:23 UTC, tancnle commented on docs/products/ontrack/project-epics/documentation-epic.md
> +## Acceptance criteria(Informal)
**nitpick:** 

```suggestion
## Acceptance criteria (Informal)
```

2022-04-07 10:21 UTC, j-6 commented
Thank you @tancnle, I've made those changes. I'm going to keep this PR open if that's OK, I would like my team to add to this PR with other project epics.

2022-04-07 10:35 UTC, tancnle commented
> Thank you @tancnle, I've made those changes. 

Thanks @j-6 👍🏼 

> I'm going to keep this PR open if that's OK, I would like my team to add to this PR with other project epics.

I would suggest keeping this PR as small as possible and merging. This work has been reviewed. Your team can create separate PR per project epic. What do you think?

2022-04-07 10:36 UTC, tancnle approved these changes

2022-04-07 11:34 UTC, merged